### ISSUE TITLE
Installing Python via Anaconda, possibly using Jupyter Lab instead of PyCharm?

### ISSUE THREAD

**Issue by mbonsma** [ladieslearningcode/llc-intro-to-python#58]
Hi! I'm an instructor in Toronto, and I just finished teaching the LLC Python material for the second time. I wanted to share a few things I noticed while teaching and hear what the community thinks about potentially using Anaconda and Jupyter Lab for the installation and lesson. (Feel free to direct this discussion elsewhere if this isn't the right venue!)

I'm a big fan of Jupyter notebooks, and the new Jupyter Lab upgrade is (in my opinion) a great tool for people doing data science and for learning. It comes by default with new installations of Python with Anaconda. Anaconda also comes with several packages that are likely to be handy for people working with data (`pandas` , `seaborn`, and maybe `scikit-learn` in particular). 

I appreciate that it's great to keep it simple at the beginning by only using what comes with base Python, but I've had success teaching beginners in the Jupyter Lab environment and I'd be interested in trying it out with this lesson. I have found that PyCharm can be tricky to use for live-coding demonstrations - there are lots of windows which makes the screen space seem cluttered and confusing. 

What do you think about (a) recommending Anaconda for installing Python, and (b) using Jupyter Lab as the interface?

Thanks,
Madeleine

**Comment by dmilliken** [comment]
Hey there! You comment comes at an interesting time. We have been updating the workshop content from python 2.7 to 3.6 and the newer installation is such a shambles for mac users. I would be interested in exploring other tools if they can help relieve the pain. 

Do you work downtown? I would love to meet up to discuss.

**Comment by mbonsma** [comment]
Yes, I do! I'd love to chat more about this. I'm based at the UofT St. George campus but happy to go anywhere in downtown. Thanks!

**Comment by jenfly** [comment]
Hi @mbonsma and @dmilliken, I've been mentoring this workshop in Vancouver for the past several months and I strongly agree with the suggestion of using Anaconda for Python installation, and possibly switching to Jupyter Lab as the development environment.

Of the workshop participants I've spoken with, at least half of them do a lot of data wrangling and data analysis in their jobs and they are keen to try Python for these tasks because they are frustrated with spreadsheets or other tools that they've been using. When they set up their development environment for the workshop by just installing core Python from python.org (or using the system Python on Mac), it makes the next steps quite difficult to transition from their workshop setup to an environment where they can install and manage all the 3rd party libraries they need to actually start crunching data -- they would have to muck around with pip installs, and virtual environments on Mac to avoid messing up the system Python.

If they install Anaconda right off the bat, they are automatically set up with an isolated environment that has all the 3rd party libraries they need so they can dive in and start learning pandas, matplotlib, etc, without even needing to understand yet what a virtual environment is or how to manage packages on their own. I think using Anaconda is also the best option for any beginner starting out, even if their ultimate goal isn't necessarily data analysis, because again it sets them up with an isolated environment where they can easily install 3rd party libraries without interfering with any system Python installations.

I recently taught a data analysis workshop for PyLadies and compiled some instructions for Anaconda / Miniconda installation [here](https://jenfly.github.io/pydata-intro-workshop/SETUP). I'd be happy to adapt these materials for the Ladies Learning Code workshop, if that would be helpful. 

On the flip side, my biggest concern about Anaconda is that it is BIG and takes a long time to install, which makes it essential that everyone install it ahead of time, before the workshop. We always have at least a few who haven't installed the software yet when they arrive at the workshop, so this would be problematic. Miniconda is much faster to download and install, but requires working at the command line, which could be intimidating to beginners who are brand new to coding.

If we stick with PyCharm as the development environment, I'm fairly sure that this will work pretty easily for Windows users - if they install Anaconda and PyCharm, PyCharm will automatically detect Anaconda and set it as the default project interpreter. For Mac users, since there's already a system installation of Python and it sounds like PyCharm tends to set this one as the default rather than Anaconda, they would have to follow some additional steps to change the project interpreter. I previously compiled some instructions for this [here](https://jenfly.github.io/llc-python-resources/pycharm-anaconda.html). Of course, all this manual configuration is not ideal when we want to keep the setup as simple as possible for students.

Regarding PyCharm vs. Jupyter Lab, I do think Jupyter Lab could potentially be a much better environment for teaching and learning. As @mbonsma pointed out, PyCharm is quite tricky for live demonstrations, and the font size is so tiny that it's always really hard for people in the back to read it (neither I nor any of the instructors I've mentored with so far have found any way to adjust this). From my perspective as a mentor, I spend a *lot* of time just helping people sort out all sorts of weird hiccups and quirks of PyCharm. It likes to keep a lot of things hidden, even simple things like when you click "run" to run a script, which folder is it running out of? It's not necessarily the folder that the script is in, and we always have to spend a bunch of time trying out different relative file paths in order to actually read in the csv files for the exercises.

When I use Jupyter Lab for live demos and teaching, I can make the font as huge as I want by simply zooming in the browser. I feel like it's also a less cluttered environment and easier to find things compared to PyCharm. I think working in Jupyter notebooks could also be easier for students compared to switching around between the Python console and scripts in PyCharm. And since this workshop is billed as "Data Insights with Python", and Jupyter Lab is a much better environment for analyzing data than PyCharm (in my hugely biased opinion as a scientist), I do think Jupyter Lab would be much better.

Of course, switching to Jupyter Lab would require a more extensive overhaul of the workshop slides, beyond just the initial slides with installation instructions. I do think this would be a worthwhile endeavour and would be very happy to help make these changes, if that's the direction we decide to go in. I'm curious, how do these decisions typically get made? Who are the go-to people for managing the content of this workshop?

I'd love to discuss this further here or via email / Slack / Skype, whatever is easiest. Thanks!

**Comment by mbonsma** [comment]
Also @jenfly I did manage to increase the font size in PyCharm but it's way buried in the settings menu.

**Comment by dmilliken** [comment]
@mbonsma That's tricky. Our philosophy has always been to be accessible to beginners but there is (as far as I know) growing demand for python content among our learner community. It's hard to do anything interesting when 60% of the day is spent learning the basics. 

How big is the installation for these other tools? The other thing that is is very important is that we cannot assume that the workshops have internet access. The files all need to fit on reasonable-sized USB sticks for those chapters that do not have connectivity in their venues.

**Comment by mbonsma** [comment]
The [Anaconda installer](https://www.anaconda.com/download/#windows) file is between 600 and 630 MB depending on OS, and it can take a while to install on older or slower machines (like tens of minutes). That's not too big for a reasonable 2 GB USB stick, and I've used it at lots of workshops without too much pain installing, as long as people come early enough that we can help them debug if it doesn't work. 

I just love Jupyter a lot, and anecdotally it works great for beginner workshops, so I would advocate for a Jupyter / Anaconda workshop to still be a beginner course. I think it's possible to get to cool stuff pretty early on, as long as you're willing to sacrifice some topics that won't be used later in the lesson. A drastic example is that you could skip `for` loops if you start using `pandas` right away. I know many programmers would think that's heresy (and I kind of agree), but there are definitely a few corners that can be cut if your goal for the workshop is analyzing spreadsheet-like data.

**Comment by dmilliken** [comment]
Closing issue -- there is nothing to do for this particular workshop, will review with participants/HQ offline.

**Comment by jenfly** [comment]
@dmilliken, keeping the workshop as is and potentially developing a new data-oriented level 2 workshop sounds like a great plan. At least here in Vancouver there seems to be a lot of interest. I'd love to help create such a workshop - how do I get involved? Do you have a Slack channel or other forum for folks to talk about developing new content?

@mbonsma, it sounds like we are involved in very similar Python teaching pursuits - I would love to discuss further! I found your contact info on your profile and will send you an email 😃

**Comment by dmilliken** [comment]
Hey @jenfly  I'm meeting with the content lead this week, I'll bring it up! They'll weigh it against other ongoing projects/priorities/etc and I'll keep this thread updated.

**Comment by jenfly** [comment]
Awesome, thanks @dmilliken!
